# Workflow file of GitHub Actions

name: build

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os: [  linux ]
        arch: [ amd64 ]
        go: [ '1.18' ]
        exclude:
          # windows excludes
          - os: windows
            arch: arm64
        include:
#          # combine runs on
#          - os: darwin
#            runs-on: macos-13
#          - os: darwin
#            arch: arm64
#            runs-on: macos-latest
          - os: linux
            runs-on: ubuntu-latest
#          - os: windows
#            runs-on: windows-latest

    steps:
      - name: list version
        shell: bash
        run: |
          sudo apt-get update
          sudo apt list -a qemu-user-static
          
           
