# Workflow file of GitHub Actions

name: build

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os: [ darwin, linux, windows ]
        arch: [ amd64, arm64 ]
        go: [ '1.18' ]
        exclude:
          # windows excludes
          - os: windows
            arch: arm64
        include:
          # combine runs on
          - os: darwin
            runs-on: macos-13
          - os: darwin
            arch: arm64
            runs-on: macos-latest
          - os: linux
            runs-on: ubuntu-latest
          - os: windows
            runs-on: windows-latest

    steps:
      - name: Checkout scm
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Get GOPATH
        id: get-gopath
        shell: bash
        run: |
          echo "GOPATH=${GOPATH}"
          echo "PATH=${PATH}"
          echo ==
          GOPATH=$(go env GOPATH)
          PATH=$PATH:"${GOPATH}/bin"
          echo ==          
          echo "GOPATH=${GOPATH}"
          echo "PATH=${PATH}" 

      - name: print
        shell: bash
        run: |
          echo ==          
          echo "GOPATH=${GOPATH}"
          echo "PATH=${PATH}" 
          echo "GOPATH: %GOPATH%"
          echo "PATH: %PATH%"
